production:
        secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
        stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY_PRODUCTION'] %>
        stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY_PRODUCTION'] %>

development:
  # stripe
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
